apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
  labels:
    app: elastic
spec:
  releaseName: elastic
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m
  targetNamespace: elk
  install:
    createNamespace: true 
  values:
    replicas: 1
    minimumMasterNodes: 1
    esConfig: 
      elasticsearch.yml: | 
        xpack.security.enabled: false
        xpack.security.transport.ssl.enabled: false
        xpack.security.http.ssl.enabled: false
        path.data: /usr/share/elasticsearch/data
    # extraEnvs:
    #   - name: xpack.security.enabled
    #     value: false  

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: logstash
#   namespace: flux-system
#   labels:
#     app: logstash
# spec:
#   releaseName: logstash
#   interval: 5m
#   chart:
#     spec:
#       chart: logstash
#       version: '8.5.1'
#       sourceRef:
#         kind: HelmRepository
#         name: elastic-charts
#         namespace: flux-system
#       interval: 1m
#   targetNamespace: elk
#   install:
#     createNamespace: true 
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: kibana
#   namespace: flux-system
#   labels:
#     app: kibana
# spec:
#   releaseName: kibana
#   interval: 5m
#   chart:
#     spec:
#       chart: kibana
#       version: '8.5.1'
#       sourceRef:
#         kind: HelmRepository
#         name: elastic-charts
#         namespace: flux-system
#       interval: 1m
#   targetNamespace: elk
#   install:
#     createNamespace: true 




