apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  releaseName: elasticsearch
  chart:
    repository: elastic-charts
    name: elasticsearch
    version: 8.5.1
  values:
    clusterName: my-cluster
    replicas: 1
    minimumMasterNodes: 1


