apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
  labels:
    app: elastic
spec:
  releaseName: elastic
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m
  values:
    replicas: 1
    minimumMasterNodes: 1
    protocol: https
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: flux-system
  labels:
    app: logstash
spec:
  releaseName: logstash
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.elastic.cometadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
  labels:
    app: fluent
spec:
  releaseName: kfluent-bit
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: '0.42.0'
      sourceRef:
        kind: HelmRepository
        name: fluent 
        namespace: flux-system
      interval: 1m



