apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
  labels:
    app: elastic
spec:
  releaseName: elastic
  interval: 5m
  chart:
    spec:
      chart: elasticsearch
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m
  values:
    replicas: 1
    minimumMasterNodes: 1
    esConfig: 
      elasticsearch.yml: | 
        xpack.security.enabled: false

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: flux-system
  labels:
    app: logstash
spec:
  releaseName: logstash
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      enabled: true
    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.enabled: false
    logstashPipeline: 
    logstash.conf: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => "http://elasticsearch-master.flux-system.svc.cluster.local:9200"
            manage_template => false
            index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
            document_type => "%{[@metadata][type]}"
          }
        }

    service:
      type: ClusterIP
      ports:
        - name: beats
          port: 5044
          protocol: TCP
          targetPort: 5044
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
  labels:
    app: kibana
spec:
  releaseName: kibana
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: '8.5.1'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 1m




