
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
  labels:
    app: fluent
spec:
  releaseName: fluent-bit
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: '0.42.0'
      sourceRef:
        kind: HelmRepository
        name: fluent 
        namespace: flux-system
      interval: 1m
  targetNamespace: elk
  install:
    createNamespace: true 